// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Inventory struct {
	PlayerID string `json:"playerId"`
}

type Item struct {
	ID   string `json:"ID"`
	Name string `json:"Name"`
}

type Query struct {
}
